### ISSUE TITLE
Keep mobile phone's display on

### ISSUE THREAD

**Issue by jackmcbrezel** [designshift/atem-tally-lite#12]
First of all thank you for all the efforts you spent in this tool. It's quite useful.

One thing which could be improved is the fact that one has to configure the phone to not turn the display off after a time. There is a small js library which I already used in a project before which forces the browser (works on both Android and iOS) to keep the display on (like when streaming a video).
You can find it here:
https://github.com/richtr/NoSleep.js/

Would be great if you could include it in this project.

**Comment by scottkuo** [comment]
Good idea. I'll look into this.

**Comment by MobliMic** [comment]
I've tried implementing this myself and have sent it to a member of my team to test before I try to create a pull request for it as I don't have access to our atem over Christmas.

Here's a link to the WIP if it's of interest [Link to commit on fork](https://github.com/MobliMic/atem-tally-lite/commit/453436f1de3d047ca3031997bf968c5c88f8ef48)

**Comment by scottkuo** [comment]
Fixed
