### ISSUE TITLE
Can't display multiple Pi's at the same time

### ISSUE THREAD

**Issue by glmerrell** [designshift/atem-tally-lite#26]
**Describe the bug**
Refresh Devices only shows one RasPi at a time, preventing me from using more than one.

**To Reproduce**
1. Fresh boot two or more RasPi's one at a time and configure for WiFi
2. On the PC App 'ATEM Tally Lite' Go to 'Pi'
3. Click on 'Refresh Devices'
4. Only a single RasPi is listed at a time even if several are online. Turn off the 
one displayed then the other shows up on the very next rescan and visaversa.

**Expected behavior**
All online RasPis should be listed so I can talk to more than one at a time.

**Desktop (please complete the following information):**
 - OS: Windows 10 Ent x64 2004 on AMD FX-6300/16GB/500GB SSD
  - AtemTallyLite Version 1.1.0 on multiple RasPi ZeroWH's

**Smartphone (please complete the following information):**
 - Device: n/a

**ATEM device (please complete the following information):**
 - Device: Atem Pro
 - Firmware Version: 8.5.3

**Additional context**
Mixing phone browsers with Pi's is OK, but still only one Pi shows up at a time.

Using the Raspberry-Wifi-Conf.service for a dynamic IP or using a static-assigned 
IP address has the same behavior. Using either solely WiFi, Ethernet, or a mix 
makes no difference.

**Comment by scottkuo** [comment]
Thanks I can confirm that this is an issue. I'll look into this.

**Comment by glmerrell** [comment]
Scott,

Thanks for checking this out. I hope I’m wrong and it’s just a mistake on my part. 

I hope I’d did the right thing posting to GitHub. If not, please let me know if you’d prefer I report things another way. 

I really appreciate you making this awesome tool available for other churches to use. 

Thanks,

Greg

**Comment by scottkuo** [comment]
@glmerrell This issue has been addressed by means of a new Raspi image release which you can pick up here: https://designshift.ca/go/atem-tally-pi-1.1.1

There's also a minor UI bug that came up on the main app, so that'll be addressed in the next release but doesn't affect the overall functionality.
