### ISSUE TITLE
Supersource compatibe?

### ISSUE THREAD

**Issue by superjodale** [designshift/atem-tally-lite#29]
Hello! Just downloaded and tried the Tally-light! Seems great!
But; I have a question about the use of supersource? When a camera is used in a supersource, is there any way I can have the tallylight to respond?
Best regards Jo Dale, Norway

**Comment by superjodale** [comment]
Just for information: I have a Atem 2 m/e production switcher:-)

**Comment by scottkuo** [comment]
This is now fully addressed in the upcoming v2 release. I'll be publishing the beta builds for v2 in the next day or so once I get on my mac for the mac builds.
