### ISSUE TITLE
Dependency on Nodejs

### ISSUE THREAD

**Issue by cabintech** [designshift/atem-tally-lite#4]
Any idea if it is practical to run the server side of this without Nodejs (in particular, in a browser)? I don't see much nodejs in the code, but I think it may be in the dependencies, e.g AtemController(). My use case is that I want to embed this (server side) into an OBS custom browser dock.

Thanks for any ideas (or tell me it is impossible...)
-Mark

**Comment by cabintech** [comment]
Well, I was able to write a new client in an OBS browser dock to show tally status with each camera control dock:
![obs](https://user-images.githubusercontent.com/31935300/92017656-19752500-ed22-11ea-87a5-78a0ba5aedeb.png)

The code is trivial (once I figured it out), just changing the color of a DIV (the green and red stripes in the screen shot) based on the tally events. In my OBS browser app javascript:

```
var socket = io('http://localhost:3777'); // Connect to tally server running on this machine
socket.on('update_tally', function(msg) {
	if ((msg.previewSourceId == cameraNum) && (msg.programSourceId == cameraNum)) { // Both pgm and preview
		$("#tally-div").css("background-color", "#FFFF00");
	}
	else if (msg.previewSourceId == cameraNum) {
		$("#tally-div").css("background-color", "#00FF00");
	}
	else if (msg.programSourceId == cameraNum) {
		$("#tally-div").css("background-color", "#FF0000");
	}
	else {
		$("#tally-div").css("background-color", "#000000");
	}
});
```

This requires that the Tally application be running on the same box as OBS. I would really prefer to embed everything in OBS but that means running NodeJS in a (OBS) browser environment...

**Comment by scottkuo** [comment]
@cabintech You could take a look at the ATEM Switchers SDK that's officially supported by Blackmagic https://www.blackmagicdesign.com/support/family/atem-live-production-switchers

**Comment by MrTomek** [comment]
@cabintech did you manage to connect it with obs? if so how?

**Comment by cabintech** [comment]
Yes, I was able to connect OBS with the tally system via an OBS "browser
dock" (e.g. it is a browser window embedded in an OBS dockable panel). See
my 2nd comment on this thread. I was able to write Javascript code in the
browser dock that gets tally events and sets red/green lights in the OBS
UI. (I started with the PTZOptics sample OBS browser dock and added the
tally code to it).
