### ISSUE TITLE
Wifi Reconnect issue after every couple hours of not being powered on

### ISSUE THREAD

**Issue by Maxiklaxi** [designshift/atem-tally-lite#40]
**Describe the bug**
My problem is the following: Im working in a Studio enviroment and every evening i shut down my "Raspberry Pi Zero W" (im currently using 4 of them).
The next morning im coming back to the studio i boot them up again for the next livestreams and i have to reconnect all of them to my wifi again, everytime when they are not powered on for something like 12 hours or so. I know that those Pi´s dont have CMOS Batteries, but shouldnt the wifi settigs be saved to the removable SD?

**Additional context**
After i put the Wifi Password into every Pi again, i have to restart all Pi´s in order to work correctly and respond to my ATEM, otherwise if i dont restart them, every one of them is just lighting up and are possible to find inside the ATEM Tally Lite Tool, but dont respond to the "Identify" button and neither the ATEM, but i guess this is just normal and a setup thing, but a automatic reboot after the Pi gets a Wifi Connection would be awesome and very helpful. 

But it would be awesome if i could connect them to my wifi for once and then be "Plug and Play" after that forever.

Everything else works perfectly fine and im very happy with the solution because my borrow performers now know in which camera to look and highers my production value a lot!

Appreciate your work!!

**Comment by scottkuo** [comment]
@Maxiklaxi Please take a look on the website for instructions on turning off AP mode on the Pi devices

https://designshift.ca/apps/atem-tally/ (Scroll down to the FAQ section)
