### ISSUE TITLE
how about an option to add vibration to signal?

### ISSUE THREAD

**Issue by techaggi** [designshift/atem-tally-lite#50]
what if the camera operator can not see the tally on the handy but would notice a vibration in his pocket - first signal > he is on air - next signal > he is off air -  there is the risk of some flaws - but in generel it could help. if the effort to progam it is reasonable (with on/off switch) i think its a benefit for the whole app.

**Comment by scottkuo** [comment]
@techaggi Looks like this is now supported with Android devices. I can take a look at rolling it into the web client for v2. I think default will be off and it'll have to be turned on in settings since most people have the devices fixed on their cameras.
