### ISSUE TITLE
Mobile view requires an internet connection

### ISSUE THREAD

**Issue by scottkuo** [designshift/atem-tally-lite#7]
**Describe the bug**
The mobile view does not load if the phone does not have an internet connection available.

**To Reproduce**
1. Disconnect router from internet access and disable all other network access on the mobile device other than wifi
2. Connect to ATEM Tally mobile view

**Expected behavior**
Page should load with a list of cameras if the main computer was able to load status correctly

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version ATEM Tally <1.1

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**ATEM device (please complete the following information):**
 - Device: All
 - Firmware Version: All

**Additional context**
Mobile view loads jQuery from internet.

**Comment by tfe** [comment]
Agreed, it’d be great to serve all necessary assets from the desktop app.

Ideally I’d want to run this system on our dedicated production control VLAN which has no internet access.

**Comment by scottkuo** [comment]
Fixed in upcoming release
